//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRunDragon.AuthenService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.authentication.vdsc.com", ConfigurationName="AuthenService.AuthenService")]
    public interface AuthenService {
        
        // CODEGEN: Generating message contract since element name jsonPwdInfo from namespace http://services.authentication.vdsc.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        WebRunDragon.AuthenService.checkAuthenResponse checkAuthen(WebRunDragon.AuthenService.checkAuthenRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<WebRunDragon.AuthenService.checkAuthenResponse> checkAuthenAsync(WebRunDragon.AuthenService.checkAuthenRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkAuthenRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkAuthen", Namespace="http://services.authentication.vdsc.com", Order=0)]
        public WebRunDragon.AuthenService.checkAuthenRequestBody Body;
        
        public checkAuthenRequest() {
        }
        
        public checkAuthenRequest(WebRunDragon.AuthenService.checkAuthenRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.authentication.vdsc.com")]
    public partial class checkAuthenRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string jsonPwdInfo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string jsonAuthenInfo;
        
        public checkAuthenRequestBody() {
        }
        
        public checkAuthenRequestBody(string jsonPwdInfo, string jsonAuthenInfo) {
            this.jsonPwdInfo = jsonPwdInfo;
            this.jsonAuthenInfo = jsonAuthenInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkAuthenResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkAuthenResponse", Namespace="http://services.authentication.vdsc.com", Order=0)]
        public WebRunDragon.AuthenService.checkAuthenResponseBody Body;
        
        public checkAuthenResponse() {
        }
        
        public checkAuthenResponse(WebRunDragon.AuthenService.checkAuthenResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://services.authentication.vdsc.com")]
    public partial class checkAuthenResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string checkAuthenReturn;
        
        public checkAuthenResponseBody() {
        }
        
        public checkAuthenResponseBody(string checkAuthenReturn) {
            this.checkAuthenReturn = checkAuthenReturn;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AuthenServiceChannel : WebRunDragon.AuthenService.AuthenService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AuthenServiceClient : System.ServiceModel.ClientBase<WebRunDragon.AuthenService.AuthenService>, WebRunDragon.AuthenService.AuthenService {
        
        public AuthenServiceClient() {
        }
        
        public AuthenServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AuthenServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AuthenServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebRunDragon.AuthenService.checkAuthenResponse WebRunDragon.AuthenService.AuthenService.checkAuthen(WebRunDragon.AuthenService.checkAuthenRequest request) {
            return base.Channel.checkAuthen(request);
        }
        
        public string checkAuthen(string jsonPwdInfo, string jsonAuthenInfo) {
            WebRunDragon.AuthenService.checkAuthenRequest inValue = new WebRunDragon.AuthenService.checkAuthenRequest();
            inValue.Body = new WebRunDragon.AuthenService.checkAuthenRequestBody();
            inValue.Body.jsonPwdInfo = jsonPwdInfo;
            inValue.Body.jsonAuthenInfo = jsonAuthenInfo;
            WebRunDragon.AuthenService.checkAuthenResponse retVal = ((WebRunDragon.AuthenService.AuthenService)(this)).checkAuthen(inValue);
            return retVal.Body.checkAuthenReturn;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebRunDragon.AuthenService.checkAuthenResponse> WebRunDragon.AuthenService.AuthenService.checkAuthenAsync(WebRunDragon.AuthenService.checkAuthenRequest request) {
            return base.Channel.checkAuthenAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebRunDragon.AuthenService.checkAuthenResponse> checkAuthenAsync(string jsonPwdInfo, string jsonAuthenInfo) {
            WebRunDragon.AuthenService.checkAuthenRequest inValue = new WebRunDragon.AuthenService.checkAuthenRequest();
            inValue.Body = new WebRunDragon.AuthenService.checkAuthenRequestBody();
            inValue.Body.jsonPwdInfo = jsonPwdInfo;
            inValue.Body.jsonAuthenInfo = jsonAuthenInfo;
            return ((WebRunDragon.AuthenService.AuthenService)(this)).checkAuthenAsync(inValue);
        }
    }
}
