// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebRunDragon.Forms
{


    public partial class QLDieuChinhKho
    {

        protected global::System.Web.UI.ScriptManager ScriptManager1;

        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        protected global::DevExpress.Web.ASPxButton btnSearch;

        protected global::DevExpress.Web.ASPxGridView gridQLDieuChinhKho;

        protected global::System.Web.UI.WebControls.SqlDataSource SqlDataSourceDieuChinhKho;

        protected global::DevExpress.Web.ASPxHiddenField txtObjectId;

        protected global::DevExpress.Web.ASPxHiddenField txtObjectDetailId;

        protected global::DevExpress.Web.ASPxPopupControl popUpdateForm;

        protected global::DevExpress.Web.PopupControlContentControl PopupControlContentControl1;

        protected global::DevExpress.Web.ASPxPageControl ASPxTabControl1;

        protected global::DevExpress.Web.ASPxComboBox cbMaChiNhanh;

        protected global::DevExpress.Web.ASPxDateEdit deNgayNhap;

        protected global::DevExpress.Web.ASPxTextBox txtSoPhieuNhap;

        protected global::DevExpress.Web.ASPxComboBox cbKhoNhap;

        protected global::DevExpress.Web.ASPxComboBox cbNhanVienPhieu;

        protected global::DevExpress.Web.ASPxTextBox txtGhiChu;

        protected global::DevExpress.Web.ASPxPageControl ASPxPageControl1;

        protected global::DevExpress.Web.ASPxGridView gridDetails;

        protected global::DevExpress.Web.ASPxImage ASPxImage1;

        protected global::DevExpress.Web.ASPxGridView gridAttachments;

        protected global::DevExpress.Web.ASPxUploadControl uplAttachment;

        protected global::DevExpress.Web.ASPxButton btnSaveEdit;

        protected global::DevExpress.Web.ASPxButton btnGuiDuyet;

        protected global::DevExpress.Web.ASPxButton btnCancelEdit;

        protected global::DevExpress.Web.ASPxButton btnIn;

        protected global::DevExpress.Web.ASPxMemo txtGhiChuDuyetKhongDuyet;

        protected global::DevExpress.Web.ASPxButton btnDuyet;

        protected global::DevExpress.Web.ASPxButton btnKhongDuyet;

        protected global::DevExpress.Web.ASPxGridView gridLichSuKyDuyet;

        protected global::DevExpress.Web.ASPxPopupControl popupConfirmDelete;

        protected global::DevExpress.Web.ASPxButton btnConfirmDelete;

        protected global::DevExpress.Web.ASPxButton btnCancelDelete;

        protected global::DevExpress.Web.ASPxPopupControl popUpdateDetail;

        protected global::DevExpress.Web.PopupControlContentControl PopupControlContentControl2;

        protected global::DevExpress.Web.ASPxGridView gridDanhSachTaiSan;

        protected global::DevExpress.Web.ASPxComboBox cbTaiSanDieuChinhKho;

        protected global::DevExpress.Web.ASPxLabel lbMaTaiSan;

        protected global::DevExpress.Web.ASPxLabel lbIDTonKho;

        protected global::DevExpress.Web.ASPxSpinEdit txtSoLuongCu;

        protected global::DevExpress.Web.ASPxComboBox cbTrangThaiCu;

        protected global::DevExpress.Web.ASPxSpinEdit txtSoLuongMoi;

        protected global::DevExpress.Web.ASPxComboBox cbTrangThaiMoi;

        protected global::DevExpress.Web.ASPxTextBox txtGhiChuChiTiet;

        protected global::DevExpress.Web.ASPxButton btnSaveDetail;

        protected global::DevExpress.Web.ASPxButton btnCancelSaveDetail;

        protected global::DevExpress.Web.ASPxPopupControl popConfirmDeleteDetail;

        protected global::DevExpress.Web.PopupControlContentControl PopupControlContentControl3;

        protected global::DevExpress.Web.ASPxButton btnConfirmDeleteDetail;

        protected global::DevExpress.Web.ASPxButton btnCancelDeleteDetail;

        protected global::DevExpress.Web.ASPxPopupControl ASPxPopupControl1;

        protected global::DevExpress.Web.PopupControlContentControl PopupControlContentControl21;

        protected global::DevExpress.Web.ASPxLabel lblFileName;

        protected global::DevExpress.Web.ASPxLabel lblCurrentUploadedFileLength;

        protected global::DevExpress.Web.ASPxProgressBar ASPxProgressBar1;

        protected global::DevExpress.Web.ASPxLabel lblUploadedFiles;

        protected global::DevExpress.Web.ASPxLabel lblUploadedFileLength;

        protected global::DevExpress.Web.ASPxProgressBar ASPxProgressBar2;

        protected global::DevExpress.Web.ASPxLabel lblProgressStatus;

        protected global::DevExpress.Web.ASPxButton btnCancel;

        protected global::DevExpress.Web.ASPxPopupControl popConfirm4DeletingAttach;

        protected global::DevExpress.Web.PopupControlContentControl PopupControlContentControl7;

        protected global::DevExpress.Web.ASPxButton btnDoDeleteAttach;

        protected global::DevExpress.Web.ASPxHiddenField hddAttachId;
    }
}
